version: '3'

vars:
  SRC_DIR: '{{.ROOT_DIR}}/controller/app'

include:
  project: './Project.yml'

tasks:
  build:
    deps: 
      - task: :project:update
    internal: true
    cmds:
      - west build -p -b {{.BOARD}} -s {{.SRC_DIR}}

  nucleo_f303re:
    cmds:
      - task: build
        vars:
          BOARD: nucleo_f303re
