version: '3'

vars:
  SRC_DIR: '{{.ROOT_DIR}}/app'

tasks:
  init:
    cmds:
      - west init -l {{.SRC_DIR}}
    status:
      - test -d {{.ROOT_DIR}}/.west

  update:
    cmds:
      - west update
